plugins {
    id 'java-library'
    alias(libs.plugins.teavm)
}

repositories {
    mavenCentral()
    maven {
        url = "https://maven.fabricmc.net"
    }
    mavenLocal()
}

dependencies {
    api libs.asm
    api libs.asm.util
    api libs.teavm.core
    api libs.tiny.remapper
    testImplementation libs.teavm.jso
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

sourceSets {
    dummy1
    dummy2
    dummy3
}

tasks.register('dummy1Jar', Jar) {
    from sourceSets.dummy1.output
    archiveBaseName = 'dummy1'
    archiveClassifier = ''
}

tasks.register('dummy2Jar', Jar) {
    from sourceSets.dummy2.output
    archiveBaseName = 'dummy2'
    archiveClassifier = ''
}

tasks.register('dummy3Jar', Jar) {
    from sourceSets.dummy3.output
    archiveBaseName = 'dummy3'
    archiveClassifier = ''
}

teavm {
    all {
        mainClass = "mcsrc.Indexer"
    }
    js {
        moduleType = org.teavm.gradle.api.JSModuleType.ES2015
        optimization = org.teavm.gradle.api.OptimizationLevel.AGGRESSIVE
        sourceMap = true
        obfuscated = false
    }
    wasmGC {
        addedToWebApp = true
        modularRuntime = true
        obfuscated = false
        sourceMap = true
        optimization = org.teavm.gradle.api.OptimizationLevel.AGGRESSIVE
    }
}

tasks.named("build") {
    dependsOn tasks.generateJavaScript
    dependsOn tasks.generateWasmGC
    dependsOn tasks.copyWasmGCRuntime
    dependsOn tasks.dummy1Jar
    dependsOn tasks.dummy2Jar
    dependsOn tasks.dummy3Jar
}