mapClass|mcsrc.teavm.KeySetView=java.util.concurrent.ConcurrentHashMap$KeySetView
mapClass|mcsrc.teavm.LineNumberReader=java.io.LineNumberReader
mapClass|mcsrc.teavm.TypeNotPresentException=java.lang.TypeNotPresentException